#!/bin/bash
# MOKA 生产环境 PDF 解析模块修复脚本
# 执行日期：2026-04-02
# 修复 Bug #1: 导入简历时个人信息导入不全

echo "======================================"
echo "MOKA 生产环境 PDF 解析模块修复"
echo "======================================"
echo ""

# SSH 连接信息
SSH_USER="malong"
SSH_HOST="10.10.2.131"
SSH_PASS="malong"

echo "请手动执行以下步骤："
echo ""
echo "1. SSH 登录生产环境"
echo "   ssh ${SSH_USER}@${SSH_HOST}"
echo "   密码：${SSH_PASS}"
echo ""
echo "2. 找到 Moka 后端目录（根据实际部署位置）"
echo "   cd /opt/moka-opencode/backend"
echo "   # 或"
echo "   cd /home/malka/moka-opencode/backend"
echo ""
echo "3. 检查 pdf-parse 是否安装"
echo "   ls -la node_modules/pdf-parse/"
echo ""
echo "4. 如果不存在，重新安装依赖"
echo "   npm install"
echo "   # 或"
echo "   bun install"
echo ""
echo "5. 验证 pdf-parse 版本"
echo "   npm list pdf-parse"
echo "   # 应该显示：pdf-parse@1.1.1"
echo ""
echo "6. 重启后端服务"
echo "   # Docker 部署"
echo "   docker-compose restart backend"
echo ""
echo "   # 或直接部署"
echo "   pm2 restart all"
echo "   # 或"
echo "   systemctl restart moka-backend"
echo ""
echo "7. 查看日志确认 PDF 解析正常"
echo "   docker-compose logs backend | grep -i 'pdf\\|parse'"
echo ""
echo "8. 测试简历上传功能"
echo "   - 在前端上传一份 PDF 简历"
echo "   - 检查是否自动提取：姓名、电话、邮箱"
echo ""
echo "======================================"
echo "预期结果："
echo "- 简历上传后自动解析个人信息"
echo "- 姓名、电话、邮箱字段自动填充"
echo "- 无需手动填写"
echo "======================================"
echo ""
echo "如仍有问题，请收集以下信息："
echo "1. 后端错误日志"
echo "2. 上传的 PDF 文件样本"
echo "3. 前端网络请求的响应内容"
echo ""
